Numpy Task-3

In [2]:
import numpy as np

###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [36]:
a = np.random.randint(0,100,12).reshape(3,4)
a

array([[40, 99, 41, 84],
       [44, 35, 69, 47],
       [27, 35, 93, 91]])

In [37]:
np.sort(a)

array([[40, 41, 84, 99],
       [35, 44, 47, 69],
       [27, 35, 91, 93]])

In [38]:
a[a[:,1].argsort()]

array([[44, 35, 69, 47],
       [27, 35, 93, 91],
       [40, 99, 41, 84]])

In [39]:
a[np.max(a,axis=1).argsort()[::-1]]

array([[40, 99, 41, 84],
       [27, 35, 93, 91],
       [44, 35, 69, 47]])

In [40]:
np.sort(a,axis=None).reshape(a.shape)

array([[27, 35, 35, 40],
       [41, 44, 47, 69],
       [84, 91, 93, 99]])

###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [73]:
marks = np.array([[13, 10,  9, 33],[63, 46, 90, 42],[39, 76, 13, 29],[82,  9, 29, 78],[67, 61, 59, 36]])
marks

array([[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]])

In [74]:
extra_subject = np.array([41, 87, 72, 36, 92])
extra_subject

array([41, 87, 72, 36, 92])

In [75]:
# i. Add marks every student of an extra subject in the same array.
marks = np.concatenate((marks,np.expand_dims(extra_subject,axis=1)),axis=1)
marks

array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92]])

In [76]:
rec1 = np.array([77, 83, 98, 95, 89])
rec2 = np.array([92, 71, 52, 61, 53])

In [77]:
# ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
marks = np.concatenate((marks,[rec1,rec2]),axis=0)
marks

array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92],
       [77, 83, 98, 95, 89],
       [92, 71, 52, 61, 53]])

In [81]:
# iii. Add extra column with sum of all subjects(5-subjects) marks
marks_with_total = np.concatenate((marks,np.expand_dims(np.sum(marks,axis=1),axis=1)),axis=1)
marks_with_total

array([[ 13,  10,   9,  33,  41, 106],
       [ 63,  46,  90,  42,  87, 328],
       [ 39,  76,  13,  29,  72, 229],
       [ 82,   9,  29,  78,  36, 234],
       [ 67,  61,  59,  36,  92, 315],
       [ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329]])

In [88]:
# iv. Sort the array(non-ascending order) on total marks column -> one added in above task. Show top 2 rows.
marks_with_total[marks_with_total[:,-1].argsort()[::-1]][:2]

array([[ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329]])

###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [89]:
arr = np.array([[1,2,3,3,1,1],[0,9,1,2,8,8],[1,2,3,8,8,8],[1,2,3,3,1,1]])
arr

array([[1, 2, 3, 3, 1, 1],
       [0, 9, 1, 2, 8, 8],
       [1, 2, 3, 8, 8, 8],
       [1, 2, 3, 3, 1, 1]])

In [90]:
np.unique(arr,axis=0)

array([[0, 9, 1, 2, 8, 8],
       [1, 2, 3, 3, 1, 1],
       [1, 2, 3, 8, 8, 8]])

In [91]:
np.unique(arr,axis=1)

array([[1, 1, 2, 3, 3],
       [0, 8, 9, 1, 2],
       [1, 8, 2, 3, 8],
       [1, 1, 2, 3, 3]])

###`Q-4:` Flip given 2-D array along both axes at the same time.

In [30]:
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[19, 80, 41, 35],
       [66, 82, 25, 54],
       [75, 31, 83, 34],
       [32, 81,  6, 58],
       [52, 12, 61, 14],
       [52,  1, 54, 74]])

In [31]:
np.flip(a)

array([[74, 54,  1, 52],
       [14, 61, 12, 52],
       [58,  6, 81, 32],
       [34, 83, 31, 75],
       [54, 25, 82, 66],
       [35, 41, 80, 19]])

### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [109]:
a = np.array([[1,2,3,4,5],[10,-3,30,4,5],[3,2,5,-4,5],[9,7,3,6,5]])
X = 6
print(a,X,sep="\n\n")

[[ 1  2  3  4  5]
 [10 -3 30  4  5]
 [ 3  2  5 -4  5]
 [ 9  7  3  6  5]]

6


In [110]:
np.unique(np.where(a>X)[0])

array([1, 3])

### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [170]:
def flat_array(*args):
  res = []
  for i in args:
    res.extend(np.ravel(i))
  return np.array(res)

In [171]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(15).reshape(3,5)
arr4 = np.arange(10,16).reshape(2,3)

In [172]:
flat_array(arr1,arr2,arr3,arr4)

array([ 0,  1,  2,  3,  4,  5,  6,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
       10, 11, 12, 13, 14, 10, 11, 12, 13, 14, 15])

### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [49]:
np.random.seed(400)
a = np.random.randint(100, 1000, 200).reshape((1, 200))
a

array([[448, 563, 418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458,
        387, 262, 613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967,
        277, 470, 336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592,
        997, 137, 340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932,
        645, 952, 921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251,
        957, 103, 627, 920, 824, 356, 825, 173, 323, 372, 960, 710, 464,
        244, 782, 763, 635, 436, 774, 171, 469, 178, 458, 624, 211, 771,
        270, 308, 231, 952, 514, 699, 702, 433, 900, 373, 318, 998, 265,
        503, 320, 230, 324, 922, 967, 620, 743, 527, 117, 566, 804, 123,
        946, 587, 227, 853, 757, 944, 328, 855, 930, 325, 729, 426, 514,
        296, 879, 575, 936, 705, 209, 191, 743, 510, 513, 628, 559, 658,
        528, 395, 525, 922, 136, 496, 225, 895, 975, 263, 908, 420, 711,
        800, 976, 786, 235, 930, 859, 618, 226, 695, 460, 218, 483, 490,
        803, 621, 453, 193, 607, 677, 637, 728, 724

In [50]:
np.min(a)

103

In [51]:
np.max(a)

998

In [52]:
np.delete(a,[np.argmin(a),np.argmax(a)])

array([448, 563, 418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458,
       387, 262, 613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967,
       277, 470, 336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592,
       997, 137, 340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932,
       645, 952, 921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251,
       957, 627, 920, 824, 356, 825, 173, 323, 372, 960, 710, 464, 244,
       782, 763, 635, 436, 774, 171, 469, 178, 458, 624, 211, 771, 270,
       308, 231, 952, 514, 699, 702, 433, 900, 373, 318, 265, 503, 320,
       230, 324, 922, 967, 620, 743, 527, 117, 566, 804, 123, 946, 587,
       227, 853, 757, 944, 328, 855, 930, 325, 729, 426, 514, 296, 879,
       575, 936, 705, 209, 191, 743, 510, 513, 628, 559, 658, 528, 395,
       525, 922, 136, 496, 225, 895, 975, 263, 908, 420, 711, 800, 976,
       786, 235, 930, 859, 618, 226, 695, 460, 218, 483, 490, 803, 621,
       453, 193, 607, 677, 637, 728, 724, 534, 748, 291, 194, 76

### `Q-8:` You are given an array. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [173]:
a = np.random.randint(100,700,10)
a

array([193, 258, 660, 258, 101, 679, 106, 617, 505, 607])

In [175]:
clipped_a = np.clip(a,a_min=100,a_max=200)
clipped_a

array([193, 200, 200, 200, 101, 200, 106, 200, 200, 200])

In [176]:
np.sort(clipped_a)

array([101, 106, 193, 200, 200, 200, 200, 200, 200, 200])

In [177]:
np.cumsum(np.sort(clipped_a))

array([ 101,  207,  400,  600,  800, 1000, 1200, 1400, 1600, 1800])

### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [181]:
a = np.random.random(10)
a

array([0.3047045 , 0.14817997, 0.80627511, 0.97516652, 0.6340842 ,
       0.91418803, 0.88484205, 0.20316923, 0.10962696, 0.59357587])

In [183]:
a = np.round(a,3)
a

array([0.305, 0.148, 0.806, 0.975, 0.634, 0.914, 0.885, 0.203, 0.11 ,
       0.594])

In [184]:
np.percentile(a,0)

0.11

In [185]:
np.percentile(a,100)

0.975

In [186]:
np.percentile(a,51)-np.percentile(a,50)

0.0036000000000000476