Numpy Task-1

**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [2]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [11]:
a = np.zeros(10,dtype=int)
a[4] = 1
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [8]:
np.where(np.arange(10)==4,1,0)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [16]:
(np.arange(10)==4).astype(int)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [20]:
a = int(input("Enter the number of rows: "))
b = int(input("Enter the number of columns: "))
import random
# arr = np.round(np.random.random((a,b))*100)
arr = np.random.randint(1,100,(a,b))
print(arr)
print(np.mean(arr))

Enter the number of rows: 4
Enter the number of columns: 5
[[19 96 14 79 31]
 [43 10  4 33 30]
 [90 28 53 61 49]
 [27 64 36 44 65]]
43.8


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [27]:
def create_array(a,b):
  arr = np.ones((a,b),dtype=int)
  arr[1:-1,1:-1] = 0
  return arr

In [29]:
a = int(input("Enter the number of rows: "))
b = int(input("Enter the number of columns: "))
create_array(a,b)

Enter the number of rows: 7
Enter the number of columns: 8


array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [34]:
np.linspace(0,1,11,endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [41]:
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [31]:
help(np.linspace)

Help on _ArrayFunctionDispatcher in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, s

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [ ]:
# No, we can't create an identity matrix of shape (3,4)

In [43]:
np.identity(3,4)

TypeError: Cannot interpret '4' as a data type

In [44]:
help(np.identity)

Help on function identity in module numpy:

identity(n, dtype=None, *, like=None)
    Return the identity array.
    
    The identity array is a square array with ones on
    the main diagonal.
    
    Parameters
    ----------
    n : int
        Number of rows (and columns) in `n` x `n` output.
    dtype : data-type, optional
        Data-type of the output.  Defaults to ``float``.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. versionadded:: 1.20.0
    
    Returns
    -------
    out : ndarray
        `n` x `n` array with its main diagonal set to one,
        and all other elements 0.
    
    Examples
    --------
    >>> np.identity(3)
    

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [48]:
np.arange(5).repeat(5).reshape(5,5)

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [58]:
np.concatenate([np.arange(5) for i in range(5)]).reshape(5,5)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [60]:
np.zeros((5,5),dtype=int)+np.arange(5)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [69]:
#np.tile(np.arange(5),5).reshape(5,5)
np.tile(np.arange(5),(5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [97]:
point = np.array([2,3])

In [98]:
coordinates = np.random.randint(1,100,(10,2))
coordinates

array([[31, 45],
       [28, 44],
       [57, 13],
       [78, 14],
       [33, 87],
       [ 8, 57],
       [19, 39],
       [52, 71],
       [16, 82],
       [97, 73]])

In [99]:
distance = np.array((np.sum((coordinates - point)**2,axis=1))**0.5,dtype=int)
distance

array([ 51,  48,  55,  76,  89,  54,  39,  84,  80, 118])

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [116]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)

https://numpy.org/doc/stable/reference/generated/numpy.unravel_index.html#numpy.unravel_index

https://stackoverflow.com/questions/48135736/what-is-an-intuitive-explanation-of-np-unravel-index

In [118]:
a = np.arange(6*7*8).reshape(6,7,8)
a[1,5,3]

99

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [8]:
L = input().split()
# np.array(L[::-1],dtype=float)
np.array(L,dtype=float)[::-1]

1 2 3 4 -8 -10


array([-10.,  -8.,   4.,   3.,   2.,   1.])

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [28]:
a = np.array([[1,2],[3,4],[5,6]])
# a = np.array([])
# a = np.array([1, 2])

In [29]:
np.size(a)

6

In [12]:
help(np.size)

Help on _ArrayFunctionDispatcher in module numpy:

size(a, axis=None)
    Return the number of elements along a given axis.
    
    Parameters
    ----------
    a : array_like
        Input data.
    axis : int, optional
        Axis along which the elements are counted.  By default, give
        the total number of elements.
    
    Returns
    -------
    element_count : int
        Number of elements along the specified axis.
    
    See Also
    --------
    shape : dimensions of array
    ndarray.shape : dimensions of array
    ndarray.size : number of elements in array
    
    Examples
    --------
    >>> a = np.array([[1,2,3],[4,5,6]])
    >>> np.size(a)
    6
    >>> np.size(a,1)
    3
    >>> np.size(a,0)
    2



### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [95]:
def softmax(arr):
  try:
    if arr.ndim != 1:
      raise TypeError("Softmax function is for only 1D array")
  except Exception as e:
    print(e)
  else:
    return np.exp(arr)/np.sum(np.exp(arr))

In [96]:
l = input().split()
a = np.array(l,dtype=float)
softmax(a)

33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278


array([4.57181033e-26, 1.16249922e-20, 7.73872594e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01])

In [97]:
a = np.arange(10).reshape(2,5)
softmax(a)

Softmax function is for only 1D array


### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [87]:
def stack(*args):
  try:
    for i in args:
      if type(i) != np.ndarray:
        raise TypeError("All arguments should be numpy array")
  except Exception as e:
    print(e)
  else:
    return np.vstack(args)

In [93]:
a = np.arange(10).reshape(2,5)
b = np.ones(10,dtype=np.int8).reshape(2,5)
stack(a,b)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [94]:
c = np.random.random(10).reshape(2,5)
stack(a,b,c)

array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [5.        , 6.        , 7.        , 8.        , 9.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.99793491, 0.97983578, 0.69626093, 0.44582627, 0.49815752],
       [0.56890333, 0.62492173, 0.39585728, 0.95938503, 0.19663409]])

In [91]:
a = np.arange(10).reshape(2,5)
b = [10,11,12,13,14]
stack(a,b)

All arguments should be numpy array


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [219]:
def date_array(start,end):
  try:
    if type(start) != str or type(end) != str:
      raise TypeError("All arguments should be string")
  except Exception as e:
    print(e)
  else:
    start = np.datetime64(start)
    end = np.datetime64(end)
    return np.arange(start,end+1)
    #return np.arange(start,end+np.timedelta64(1,'D'),dtype='datetime64[D]')

In [220]:
s = '2020-11-25'
e = '2020-11-30'
print(date_array(s,e))

['2020-11-25' '2020-11-26' '2020-11-27' '2020-11-28' '2020-11-29'
 '2020-11-30']


In [221]:
date_array(start = '2020-09-15', end = '2020-09-25')

array(['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
       '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
       '2020-09-23', '2020-09-24', '2020-09-25'], dtype='datetime64[D]')

In [222]:
date_array(start = '2022-12-01', end = '2022-12-06')

array(['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04',
       '2022-12-05', '2022-12-06'], dtype='datetime64[D]')

https://numpy.org/doc/stable/reference/arrays.datetime.html#arrays-datetime

###`Q-14:` Subtract the mean of each row from a matrix.

In [195]:
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[86,  6, 51, 42],
       [63, 13, 39, 74],
       [64, 14, 48,  1],
       [58, 89, 53, 69],
       [78, 61, 39, 41],
       [63,  9, 87,  5]])

In [196]:
np.mean(a,axis=1,keepdims=True)

array([[46.25],
       [47.25],
       [31.75],
       [67.25],
       [54.75],
       [41.  ]])

In [197]:
a - np.mean(a,axis=1,keepdims=True)

array([[ 39.75, -40.25,   4.75,  -4.25],
       [ 15.75, -34.25,  -8.25,  26.75],
       [ 32.25, -17.75,  16.25, -30.75],
       [ -9.25,  21.75, -14.25,   1.75],
       [ 23.25,   6.25, -15.75, -13.75],
       [ 22.  , -32.  ,  46.  , -36.  ]])

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [156]:
def swap_columns(arr,col1,col2):
  arr[:,[col1,col2]] = arr[:,[col2,col1]]
  # arr[:,col1],arr[:,col2] = arr[:,col2].copy(),arr[:,col1].copy()
  return arr

In [167]:
a = np.arange(24).reshape(4,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [161]:
swap_columns(a,2,4)

array([[ 0,  1,  4,  3,  2,  5],
       [ 6,  7, 10,  9,  8, 11],
       [12, 13, 16, 15, 14, 17],
       [18, 19, 22, 21, 20, 23]])

In [168]:
temp = np.copy(a[:, 0])
a[:, 0] = a[:, 1]
a[:, 1] = temp
a

array([[ 1,  0,  2,  3,  4,  5],
       [ 7,  6,  8,  9, 10, 11],
       [13, 12, 14, 15, 16, 17],
       [19, 18, 20, 21, 22, 23]])

In [162]:
def swap_rows(arr,row1,row2):
  arr[[row1,row2],:] = arr[[row2,row1],:]
  return arr

In [163]:
swap_rows(a,1,3)

array([[ 0,  1,  4,  3,  2,  5],
       [18, 19, 22, 21, 20, 23],
       [12, 13, 16, 15, 14, 17],
       [ 6,  7, 10,  9,  8, 11]])

###`Q-16:` Replace odd elements in arrays with -1.

In [99]:
a = np.random.randint(1,100,30).reshape(6,5)
a

array([[73, 55, 58,  4, 54],
       [45, 67, 21, 98,  8],
       [32, 11, 74, 41, 54],
       [81, 43,  7, 24, 69],
       [53, 71,  3, 68, 31],
       [78, 75, 74, 42, 97]])

In [101]:
a[a%2!=0]=-1
a

array([[-1, -1, 58,  4, 54],
       [-1, -1, -1, 98,  8],
       [32, -1, 74, -1, 54],
       [-1, -1, -1, 24, -1],
       [-1, -1, -1, 68, -1],
       [78, -1, 74, 42, -1]])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [112]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

In [113]:
np.max((a,b),axis=0)

array([6, 3, 1, 7, 8])

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [229]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[3376, 6252, 2047, 8975, 5312],
       [2633, 8318, 1458,  743, 8177],
       [8400, 4381, 8829, 7149, 1651],
       [3828, 9290, 8238, 2786, 8397],
       [8937, 2364, 2653, 1352, 3251],
       [2521, 7703, 9089, 3198, 1724],
       [8577, 9120, 5870, 1233, 6796],
       [9772, 9946, 5118,  890, 3629]])

In [231]:
def normalize(arr):
  return (arr-np.min(arr))/(np.max(arr)-np.min(arr))

In [230]:
def normalize_colwise(arr):
  return (arr-np.min(arr,axis=0))/(np.max(arr,axis=0)-np.min(arr,axis=0))

In [236]:
def normalize_rowwise(arr):
  return (arr-np.min(arr,axis=1,keepdims=True))/(np.max(arr,axis=1,keepdims=True)-np.min(arr,axis=1,keepdims=True))

In [232]:
normalize(arr1)

array([[0.28610236, 0.59860915, 0.14169293, 0.89449093, 0.49646854],
       [0.20536781, 0.82310116, 0.07769206, 0.        , 0.80778007],
       [0.8320113 , 0.39530588, 0.87862653, 0.69607737, 0.09866348],
       [0.33521678, 0.9287189 , 0.81440835, 0.22199283, 0.83168532],
       [0.89036184, 0.17613822, 0.20754102, 0.06617407, 0.27251983],
       [0.19319787, 0.75627513, 0.90687819, 0.26676084, 0.10659568],
       [0.85124416, 0.91024666, 0.55710095, 0.05324351, 0.65772031],
       [0.98109312, 1.        , 0.47538846, 0.01597305, 0.31359339]])

In [233]:
normalize_colwise(arr1)

array([[0.11791477, 0.51279346, 0.07718517, 1.        , 0.54269197],
       [0.01544615, 0.78528093, 0.        , 0.        , 0.96738808],
       [0.81078472, 0.2660248 , 0.96592845, 0.7781827 , 0.        ],
       [0.180251  , 0.91347929, 0.8884812 , 0.24817784, 1.        ],
       [0.88484347, 0.        , 0.15659809, 0.07397959, 0.23717759],
       [0.        , 0.70416777, 1.        , 0.29822643, 0.01082123],
       [0.83519515, 0.89105777, 0.578168  , 0.05952381, 0.76267418],
       [1.        , 1.        , 0.47962259, 0.01785714, 0.29321079]])

In [237]:
normalize_rowwise(arr1)

array([[0.19183025, 0.60695727, 0.        , 1.        , 0.47127598],
       [0.24950495, 1.        , 0.09438944, 0.        , 0.98138614],
       [0.94023405, 0.38032878, 1.        , 0.76595152, 0.        ],
       [0.1602091 , 1.        , 0.83825338, 0.        , 0.86269988],
       [1.        , 0.13342123, 0.17152274, 0.        , 0.25036256],
       [0.10821453, 0.81181263, 1.        , 0.20013578, 0.        ],
       [0.93115253, 1.        , 0.5879295 , 0.        , 0.7053379 ],
       [0.98078622, 1.        , 0.46687279, 0.        , 0.30245141]])

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [129]:
def nth_largest(arr,n):
  if n<=len(arr):
    return np.sort(arr)[-n]
  else:
    raise ValueError("n should be less than or equal to length of array")

In [131]:
arr=(12,34,40,7,1,0)
nth_largest(arr,3)

12

In [134]:
nth_largest(arr,1)

40

In [133]:
nth_largest(arr,7)

ValueError: n should be less than or equal to length of array

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [119]:
a = np.array([1,2,3])

In [120]:
np.concatenate([np.repeat(a,3),np.tile(a,3)])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])